export { ConfluenceClient } from './client.js';
export type {
  Attachment,
  AttachmentsResponse,
  Body,
  Comment,
  CommentsResponse,
  ContentItem,
  ContentTreeNode,
  CreateFolderRequest,
  CreatePageRequest,
  Folder,
  Label,
  LabelsResponse,
  Page,
  PagesResponse,
  PageTreeNode,
  SearchResponse,
  SearchResultItem,
  Space,
  SpacesResponse,
  SpacesV1Response,
  UpdatePageRequest,
  User,
  Version,
} from './types.js';
export {
  AttachmentSchema,
  AttachmentsResponseSchema,
  BodySchema,
  CommentSchema,
  CommentsResponseSchema,
  CreateFolderRequestSchema,
  CreatePageRequestSchema,
  FolderSchema,
  isFolder,
  LabelSchema,
  LabelsResponseSchema,
  PageSchema,
  PagesResponseSchema,
  SearchResponseSchema,
  SearchResultItemSchema,
  SpaceSchema,
  SpacesResponseSchema,
  UpdatePageRequestSchema,
  UserSchema,
  VersionSchema,
} from './types.js';
